apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginxapp
spec:
  containers:
    - name: nginx_container
      image: nginx:1.11.9-alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx_vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx_vol
      hostPath:
        path: /data/nginx_html